const types = {
        ADD_BLOG_START: 'ADD_BLOG_START',
        ADD_BLOG_SUCCESS: 'ADD_BLOG_SUCCESS',
        ADD_BLOG_FAILURE: 'ADD_BLOG_FAILURE',

        GET_BLOGS_START: 'GET_BLOGS_START',
        GET_BLOGS_SUCCESS: 'GET_BLOGS_SUCCESS',
        GET_BLOGS_FAILURE: 'GET_BLOGS_FAILURE',

        DELETE_BLOGS_START: 'DELETE_BLOGS_START',
        DELETE_BLOGS_SUCCESS: 'DELETE_BLOGS_SUCCESS',
        DELETE_BLOGS_FAILURE: 'DELETE_BLOGS_FAILURE',

        EDIT_BLOGS_START: 'EDIT_BLOGS_START',
        EDIT_BLOGS_SUCCESS: 'EDIT_BLOGS_SUCCESS',
        EDIT_BLOGS_FAILURE: 'EDIT_BLOGS_FAILURE',

        ERROR: 'ERROR',
    }

export default types;